packages:
  - "apps/*"
  - "packages/*"

autoInstallPeers: false

allowBuilds:
  unrs-resolver: true

catalogMode: strict

engineStrict: true

injectWorkspacePackages: true

minimumReleaseAge: 1440

preferFrozenLockfile: true

saveExact: true

strictPeerDependencies: true

catalog:
  '@nestjs/config': 4.0.4
  class-transformer: 0.5.1
  class-validator: 0.15.1
  joi: 18.2.3
  redis: 6.2.0
